# Generated by Django 3.0.5 on 2023-09-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='service',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
